from ato.adict import ADict
from ato.scope import Scope

scope = Scope(config=ADict.auto())


@scope.observe(default=True)
def default(config):
    config.agents.strategy_generator = dict(
        model_id='gpt-5-mini',
        parameters=dict(
            max_tokens=25600
        )
    )
    config.agents.branches = [
        dict(
            hypothesis=dict(
                model_id='gpt-5-mini',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            reasoning=dict(
                model_id='gpt-5-mini',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            verification=dict(
                model_id='gpt-5-mini',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            )
        ),
        dict(
            hypothesis=dict(
                model_id='gpt-5-mini',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            reasoning=dict(
                model_id='gpt-5-mini',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            verification=dict(
                model_id='gpt-5-mini',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            )
        ),
        dict(
            hypothesis=dict(
                model_id='gpt-5-mini',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            reasoning=dict(
                model_id='gpt-5-mini',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            verification=dict(
                model_id='gpt-5-mini',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            )
        )
    ]
    config.agents.decision = dict(
        model_id='gpt-5.1',
        # model_id='gpt-5.1-codex',
        parameters=dict(
            # reasoning=dict(effort='high'),
            max_tokens=25600
        ),
        gcri_options=dict(
            use_code_tools=True
        )
    )
    config.agents.memory = dict(
        model_id='gpt-5-mini',
        parameters=dict(
            max_tokens=25600
        ),
        gcri_options=dict(
            use_code_tools=True
        )
    )
    config.templates = dict(
        strategy_generator='./gcri/templates/strategy_generator.txt',
        hypothesis='./gcri/templates/hypothesis.txt',
        reasoning='./gcri/templates/reasoning.txt',
        verification='./gcri/templates/verification.txt',
        decision='./gcri/templates/decision.txt',
        memory='./gcri/templates/memory.txt',
        active_memory='./gcri/templates/active_memory.txt'
    )
    config.max_iterations = 5
    config.protocols = dict(
        accept_all=True,
        aggregate_targets=['strategy', 'hypothesis', 'counter_example', 'adjustment', 'counter_strength'],
        max_tries_per_agent=3
    )
    config.use_deep_feedback = False
    config.log_dir = './gcri_logs'


@scope.observe()
def large_models(config):
    config.agents.branches = [
        dict(
            hypothesis=dict(
                model_id='gpt-5.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            reasoning=dict(
                model_id='gpt-5.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            verification=dict(
                model_id='gpt-5-mini',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            )
        ),
        dict(
            hypothesis=dict(
                model_id='gpt-5.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            reasoning=dict(
                model_id='gpt-5.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            verification=dict(
                model_id='gpt-5-mini',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            )
        ),
        dict(
            hypothesis=dict(
                model_id='gpt-5.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            reasoning=dict(
                model_id='gpt-5.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            verification=dict(
                model_id='gpt-5-mini',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            )
        )
    ]


@scope.observe()
def gpt_4_1_based(config):
    config.agents.strategy_generator = dict(
        model_id='gpt-4.1',
        parameters=dict()
    )
    config.agents.branches = [
        dict(
            hypothesis=dict(
                model_id='gpt-4.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            reasoning=dict(
                model_id='gpt-4.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            verification=dict(
                model_id='gpt-4.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            )
        ),
        dict(
            hypothesis=dict(
                model_id='gpt-4.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            reasoning=dict(
                model_id='gpt-4.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            verification=dict(
                model_id='gpt-4.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            )
        ),
        dict(
            hypothesis=dict(
                model_id='gpt-4.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            reasoning=dict(
                model_id='gpt-4.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            ),
            verification=dict(
                model_id='gpt-4.1',
                parameters=dict(
                    max_tokens=25600
                ),
                gcri_options=dict(
                    use_code_tools=True
                )
            )
        )
    ]
    config.agents.memory = dict(
        model_id='gpt-4.1',
        parameters=dict(
            options=dict(
                max_tokens=25600
            )
        )
    )
